# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
server:
  endpoint: :7050
  tls:
    mode: mtls
    cert-path: /server-certs/public-key
    key-path: /server-certs/private-key
    ca-cert-paths:
      - /server-certs/ca-certificate

block-size: 1024
block-timeout: 30s
send-config-block: true
config-block-path: /root/config/sc-genesis-block.proto.bin

logging:
  development: true
  enabled: true
  level: INFO
  name: orderer
