# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
server:
  endpoint: :5001
  tls:
    mode: mtls
    cert-path: /server-certs/public-key
    key-path: /server-certs/private-key
    ca-cert-paths:
      - /server-certs/ca-certificate
monitoring:
  server:
    endpoint: :2115

parallel-executor:
  batch-size-cutoff: 50
  batch-time-cutoff: 10ms
  channel-buffer-size: 50
  parallelism: 40

logging:
  enabled: true
  development: false
  level: INFO
  name: verifier