# Configuration for the server
server:
  # The server's endpoint configuration
  endpoint: {{ .ServerEndpoint | default "localhost:0" }}
monitoring:
  server:
    endpoint: {{ .MetricsEndpoint | default "localhost:0" }}

database:
  endpoints:
    {{- range .Endpoints.Database }}
    - {{ . }}
    {{- end }}
  username: "yugabyte"
  # TODO: pass password via environment variable
  password: "yugabyte"
  database: {{ .DB.Name }}
  load-balance: {{ .DB.LoadBalance }}
  max-connections: 10
  min-connections: 5
  retry:
    max-elapsed-time: 1h

logging:
  enabled: {{ .Logging.Enabled }}
  level: {{ .Logging.Level }}
  caller: {{ .Logging.Caller }}
  development: {{ .Logging.Development }}
  output: {{ .Logging.Output }}
  name: query
